/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1_201503393;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Panel;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Color;
import javax.imageio.ImageIO;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import jdk.internal.org.xml.sax.XMLReader;
import org.jdom2.Document;         // |
import org.jdom2.Element;          // |\ Librerías
import org.jdom2.JDOMException;    // |/ JDOM
import org.jdom2.input.SAXBuilder; // |
//import org.w3c.dom.Document;
//import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

/**
 *
 * @author Daniel De León
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    static public Lista_Diccio ld = new Lista_Diccio();
    static public int dimension;
    static public Matriz asd = new Matriz();

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnjugar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Scrabble");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jButton1.setText("Leer Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnjugar.setText("Jugar");
        btnjugar.setEnabled(false);
        btnjugar.setName(""); // NOI18N
        btnjugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjugarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel1.setText("Bienvenido");

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnjugar)
                        .addGap(17, 17, 17)))
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton2)))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(46, 46, 46)
                .addComponent(btnjugar)
                .addGap(51, 51, 51)
                .addComponent(jButton2)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("XML Files", "xml");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            cargarXml(chooser.getSelectedFile().getAbsolutePath());
            JOptionPane.showMessageDialog(null, "Archivo cargado correctamente", "OPERACIÓN EXITOSA", JOptionPane.INFORMATION_MESSAGE);
            btnjugar.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnjugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjugarActionPerformed
        //System.out.println(ld.Mostrar());
        Jugadores jd = new Jugadores();
        jd.show();
        this.dispose();
    }//GEN-LAST:event_btnjugarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        File miDir = new File(".");
        String directo="";
        try {
            directo = miDir.getCanonicalPath();
        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

            String dotPath = directo + "\\Graphviz 2.28\\bin\\dot.exe";
            System.out.println(dotPath);
        for(int i=0;i<20;i++){
            System.out.println("!!!!!!!!!!!!!!!!!!!!");
            for(int j=0;j<20;j++){
                System.out.print(" -------- "+asd.getPunteo(i,j)+" en: "+ i + "," + j);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
    
    public void cargarXml(String archivo) {
       
        SAXBuilder builder = new SAXBuilder();
        File xmlFile = new File(archivo);
        try {
            Document document = (Document) builder.build(xmlFile);

            Element rootNode = document.getRootElement();

            List list = rootNode.getChildren("dimension");
            List list_dobles = rootNode.getChildren("dobles");
            List list_triples = rootNode.getChildren("triples");
            List list_diccionario = rootNode.getChildren("diccionario");

            for (int i = 0; i < list.size(); i++) {
                Element tabla = (Element) list.get(i);
                dimension = Integer.parseInt(tabla.getText());
                asd.crearMatriz(dimension);
                System.out.println("Dimension: "+tabla.getText());
            }
            for (int i = 0; i < list_dobles.size(); i++) {
                Element tabla = (Element) list_dobles.get(i);
                List lista_campos = tabla.getChildren();

                for (int j = 0; j < lista_campos.size(); j++) {
                    Element campo = (Element) lista_campos.get(j);
                    String x = campo.getChildTextTrim("x");
                    String y = campo.getChildTextTrim("y");
                    asd.setPunteo(Integer.parseInt(x),Integer.parseInt(y),2);
                    asd.setColor(Integer.parseInt(x),Integer.parseInt(y),Color.LIGHT_GRAY);
                    System.out.println(asd.getPunteo(Integer.parseInt(x),Integer.parseInt(y))+" en: "+ x + "," + y);
                    //System.out.println("Puntos Dobles en la posicion X:"+ x + " Y: " + y);
                }
            }
            for (int i = 0; i < list_triples.size(); i++) {
                Element tabla = (Element) list_triples.get(i);
                List lista_campos = tabla.getChildren();
                
                for (int j = 0; j < lista_campos.size(); j++) {
                    Element campo = (Element) lista_campos.get(j);
                    String x = campo.getChildTextTrim("x");
                    String y = campo.getChildTextTrim("y");
                    asd.setPunteo(Integer.parseInt(x),Integer.parseInt(y),3);
                    asd.setColor(Integer.parseInt(x),Integer.parseInt(y),Color.cyan);
                    System.out.println(asd.getPunteo(Integer.parseInt(x),Integer.parseInt(y))+" en: "+ x + "," + y);
                    //System.out.println("Puntos Triples en la posicion X:"+ x + " Y: " + y);
                }
            }
            
            for (int i = 0; i < list_diccionario.size(); i++) {
                Element tabla = (Element) list_diccionario.get(i);
                List lista_campos = tabla.getChildren();

                for (int j = 0; j < lista_campos.size(); j++) {
                    Element campo = (Element) lista_campos.get(j);
                    ld.push(campo.getText());
                    //System.out.println("Palabra: " + campo.getText());
                }
            }
        } catch (IOException io) {
            System.out.println(io.getMessage());
        } catch (JDOMException jdomex) {
            System.out.println(jdomex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnjugar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
